
set tw=120

function! s:insertTestHeader()
    execute "normal! i\n#include \"\"\n#include \"doctest/doctest.h\""
    execute "normal! o\nusing namespace sym2;"
    normal! kkk$
endfunction

autocmd BufNewFile tests/*.cpp call <SID>insertTestHeader()
autocmd BufRead,BufReadPost README.md set spell spelllang=en_us

call add(g:UltiSnipsSnippetDirectories, getcwd() . '/misc')

set path=bin,src/**,include/**,tests/**

fun s:addUDLSyntax()
    syn match udl "[".]\?\<[eEa-zA-Z\.'0-9+-]\+\"\?_ex\>"
    hi link udl cppStatement
endfun

augroup ft_cpp
  autocmd!
  autocmd Syntax cpp call s:addUDLSyntax()
augroup end

set lispwords+=test-group
