
configure_file(${CMAKE_CURRENT_LIST_DIR}/chibi.sh.in ${CMAKE_BINARY_DIR}/bin/chibi
    FILE_PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
    @ONLY)

configure_file(${CMAKE_CURRENT_LIST_DIR}/lldb.start.in ${CMAKE_BINARY_DIR}/lldb.start)
